name = "raceup-backend-api"
main = "src/index.ts"
compatibility_date = "2025-12-01"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "RaceUp-User-Data"
database_id = "da5708b9-9979-44f1-a979-5a822bad00c1"

[vars]
ENVIRONMENT = "production"
ACCESS_TOKEN_EXPIRY = "900"
REFRESH_TOKEN_EXPIRY = "604800"
